notifications:
  email: false
branches:
  only:
    - master
os:
  - linux
  - osx
language: csharp
solution: ShenSharp.sln
install:
  - nuget restore ShenSharp.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ShenSharp.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./Kl.Tests/bin/Release/Kl.Tests.dll
