notifications:
  email: false
branches:
  only:
    - master
language: csharp
solution: ShenSharp.sln
install:
  - nuget restore ShenSharp.sln
  - nuget install NUnit.ConsoleRunner -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ShenSharp.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./Kl.Tests/bin/Release/Kl.Tests.dll
