notifications:
  email: false
language: csharp
install:
  - msbuild /t:Restore Kl.sln
  - msbuild /t:Restore Shen.sln
  - nuget install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory testrunner
  - mkdir packages
script:
  - msbuild /p:Configuration=Release Kl.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Kl.Tests/bin/Release/net45/Kl.Tests.dll
  - pushd ./Kl.Get/bin/Release/net45
  - mono ./Kl.Get.exe
  - popd
  - pushd ./Kl.Make/bin/Release/net45
  - mono ./Kl.Make.exe
  - popd
  - msbuild /p:Configuration=Release Shen.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Shen.Tests/bin/Release/net45/Shen.Tests.dll
  - pushd ./Shen.TestSuite/bin/Release/net45
  - mono ./Shen.TestSuite.exe
  - popd
