notifications:
  email: false
os:
  - linux
  - osx
  - windows
language: csharp
mono: none
dotnet: 3.1.1
script:
  - cd src
  - dotnet build Kl.sln
  - dotnet test Kl.sln
  - dotnet run --project Kl.Get
  - dotnet run --project Kl.Make
  - dotnet build Shen.sln
  - dotnet test Shen.sln
  - dotnet run --project Shen.TestSuite
