before_build:
  - nuget restore Kl.sln
  - nuget restore Shen.sln
  - nuget install NUnit.ConsoleRunner -Version 3.6.0 -OutputDirectory testrunner
build_script:
  - msbuild /p:Configuration=Release Kl.sln
  - .\testrunner\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe .\Kl.Tests\bin\Release\Kl.Tests.dll
  - cd .\Kl.Make.Run\bin\Release
  - Kl.Make.Run.exe
  - cd ..\..\..
  - msbuild /p:Configuration=Release Shen.sln
  - cd .\Shen.Tests\bin\Release
  - Shen.Tests.exe
  - cd ..\..\..
